---
title: Kleuren weergeven met cijfers
hero_image: images/banner.png
description: Ontdek hoe kleuren met drie cijfers kunnen worden weergegeven
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Kleuren weergeven met cijfers
