---
title: Kleuren voorstellen met cijfers
hero_image: tekeningen/banner.png
description: Kom te weten hoe kleuren voorgesteld kunnen worden door 3 cijfers
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Kleuren voorstellen met cijfers
