title: Representing colours with numbers
hero_image: images/banner.png
description: Find out how colours can be represented by three number values
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: false
interests: ""
technologies: ""
steps:
  - title: Representing colours with numbers
