title: Colour Mixing
hero_image: images/banner.png
description: generic-theory-colours description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
ingredient: false
listed: false
steps:
  - title: Colour Mixing
