---
title: Å representere farger med tall
hero_image: images/banner.png
description: Finn ut hvordan farger kan representeres av tre tall
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Å representere farger med tall
