---
title: Representerer farver med tal
hero_image: images / banner.png
description: Find ud af hvordan farver kan repræsenteres med tre tal
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Representerer farver med tal
