---
title: Representando cores com números
hero_image: images / banner.png
description: Descubra como as cores podem ser representadas por três números
original_url:
theme: protótipo de cc
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Representando cores com números
