---
title: Värien esittäminen numeroilla
hero_image: Kuvien / banner.png
description: Selvitä, kuinka värejä voidaan edustaa kolmella numerolla
original_url:
theme: CC-prototyyppi
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Värien esittäminen numeroilla
