---
title: Värien esittäminen numeroilla
hero_image: images/banner.png
description: Opi kuinka värejä voidaan esittää kolmella numerolla
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Värien esittäminen numeroilla
