---
title: Representando colores con números
hero_image: images / banner.png
description: Descubre cómo los colores se pueden representar con tres números
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Representando colores con números
