---
title: Farben mit Zahlen darstellen
hero_image: Bilder / Banner.png
description: Finde heraus, wie Farben durch drei Zahlen repräsentiert werden können
original_url:
theme: cc-Prototyp
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Farben mit Zahlen darstellen
