---
title: Farben mit Zahlen darstellen
hero_image: images/banner.png
description: Finde heraus, wie Farben durch drei Zahlen repräsentiert werden können
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Farben mit Zahlen darstellen
