---
title: Representando cores com números
hero_image: imagens/banner.png
description: Descubra como as cores podem ser representadas com três números
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Representando cores com números
