---
title: Predstavitev barv s števili
hero_image: images/banner.png
description: Spoznajte, kako lahko barve ponazorimo s tremi števili
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Ponazoritev barv s števili
