---
title: Reprezentace barev s čísly
hero_image: obrázky / banner.png
description: Zjistěte, jak mohou být barvy reprezentovány třemi čísly
original_url:
theme: cc-prototyp
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Reprezentace barev s čísly
