---
title: Reprezentace barev čísly
hero_image: images/banner.png
description: Zjisti, jak mohou být barvy reprezentovány třemi čísly
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Reprezentace barev čísly
