---
title: Színek leírása számokkal
hero_image: images/banner.png
description: Ismerd meg, hogyan lehet egy színt leírni három számmal
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Színek leírása számokkal
