---
title: A színek számozásával
hero_image: images / banner.png
description: Tudja meg, hogy a színek három számmal ábrázolhatók
original_url:
theme: cc-prototípus
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: A színek számozásával
