---
title: Värvide kujutamine numbritega
hero_image: images/banner.png
description: Uurige, kuidas saab värve kolme numbriga kujutada
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Värvide kujutamine numbritega
