---
title: Reprezentowanie kolorów za pomocą liczb
hero_image: images/banner.png
description: Dowiedz się, jak kolory mogą być reprezentowane przez trzy liczby
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Reprezentowanie kolorów za pomocą liczb
