---
title: Číselné vyjadrenie farieb
hero_image: images/banner.png
description: Zistite, ako môžu byť farby vyjadrene pomocou troch čísel
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Číselné vyjadrenie farieb
