---
title: Beskriva färger med siffror
hero_image: images/banner.png
description: Ta reda på hur färger kan beskrivas med hjälp av tre siffror
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Beskriva färger med siffror
