---
title: Beteckna f채rger med siffror
hero_image: images/banner.png
description: Ta reda p책 hur f채rger kan betecknas av tre nummer
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Beteckna f채rger med siffror
