---
title: Representerar f채rger med siffror
hero_image: images / banner.png
description: Ta reda p책 hur f채rger kan representeras av tre nummer
original_url:
theme: cc-prototyp
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Representerar f채rger med siffror
