---
title: Représenter des couleurs avec des nombres
hero_image: images/banner.png
description: Découvrez comment les couleurs peuvent être représentées par trois chiffres
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Représenter des couleurs avec des nombres
