---
title: Rappresentare i colori con numeri
hero_image: images / banner.png
description: Scopri come i colori possono essere rappresentati da tre numeri
original_url:
theme: cc-prototipo
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Rappresentare i colori con numeri
