---
title: අංක මගින් වර්ණ නියෝජනය කිරීම
hero_image: images / banner.png
description: අංක තුනකින් වර්ණ නිරූපණය කරන්නේ කෙසේදැයි සොයා බලන්න
original_url:
theme: cc-ප්‍රදර්ශකය
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - title: අංක මගින් වර්ණ නියෝජනය කිරීම
