---
title: Representing colours with numbers
hero_image: images / banner.png
description: Find out how colours can be represented by three numbers
original_url:
theme: cc-prototip
duration: 1
ingredient: true
listed: false
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Representing colours with numbers
